package improve

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/7solutions/openplus/internal/skills"
)

// Run is one recorded session's tool-call sequence.
type Run struct {
	Tools []string
}

// Pattern is a tool sequence that recurred across runs.
type Pattern struct {
	Tools []string
	// Runs is the number of distinct runs the sequence appeared in.
	Runs int
}

// MineOptions bounds the search. Zero values fall back to sane defaults rather
// than mining degenerate single-tool "patterns".
type MineOptions struct {
	// MinLength is the shortest sequence considered a pattern (default 2).
	MinLength int
	// MinRuns is how many distinct runs must contain it (default 2).
	MinRuns int
	// MaxLength caps the sequence length considered (default 8).
	MaxLength int
}

func (o MineOptions) withDefaults() MineOptions {
	if o.MinLength < 2 {
		o.MinLength = 2
	}
	if o.MinRuns < 2 {
		o.MinRuns = 2
	}
	if o.MaxLength <= 0 {
		o.MaxLength = 8
	}
	return o
}

// MinePatterns finds contiguous tool sequences that appear in at least MinRuns
// distinct runs. Frequency counts *runs*, not occurrences: a sequence repeated
// twice inside one session is one habit, not two. Results are ordered
// longest-first, then by how many runs contain them.
func MinePatterns(rs []Run, opts MineOptions) []Pattern {
	opts = opts.withDefaults()
	if len(rs) == 0 {
		return nil
	}

	// runsContaining[sequence] = set of run indices containing it.
	runsContaining := map[string]map[int]bool{}
	for runIdx, r := range rs {
		for length := opts.MinLength; length <= opts.MaxLength && length <= len(r.Tools); length++ {
			for start := 0; start+length <= len(r.Tools); start++ {
				key := strings.Join(r.Tools[start:start+length], "\x00")
				if runsContaining[key] == nil {
					runsContaining[key] = map[int]bool{}
				}
				runsContaining[key][runIdx] = true
			}
		}
	}

	var out []Pattern
	for key, runSet := range runsContaining {
		if len(runSet) < opts.MinRuns {
			continue
		}
		out = append(out, Pattern{
			Tools: strings.Split(key, "\x00"),
			Runs:  len(runSet),
		})
	}

	sort.Slice(out, func(i, j int) bool {
		if len(out[i].Tools) != len(out[j].Tools) {
			return len(out[i].Tools) > len(out[j].Tools) // longer is more specific
		}
		if out[i].Runs != out[j].Runs {
			return out[i].Runs > out[j].Runs
		}
		return strings.Join(out[i].Tools, ",") < strings.Join(out[j].Tools, ",")
	})
	return out
}

// Kind is the artifact a pattern is best distilled into.
type Kind int

const (
	// KindSkill suits a multi-step, mutating workflow worth documenting.
	KindSkill Kind = iota
	// KindSubagent suits a read-only investigation that can run in isolation.
	KindSubagent
	// KindCommand suits a short, very frequent invocation.
	KindCommand
)

func (k Kind) String() string {
	switch k {
	case KindSkill:
		return "skill"
	case KindSubagent:
		return "subagent"
	case KindCommand:
		return "command"
	default:
		return fmt.Sprintf("kind(%d)", int(k))
	}
}

// mutatingTools are the tools whose presence makes a pattern non-read-only.
var mutatingTools = map[string]bool{
	"write": true,
	"edit":  true,
	"bash":  true,
}

// SuggestKind recommends what to distill a pattern into: a short but very
// frequent sequence is a command, a read-only sequence is a subagent, and
// anything that mutates the workspace is a skill.
func SuggestKind(p Pattern) Kind {
	if len(p.Tools) <= 2 && p.Runs >= 5 {
		return KindCommand
	}
	for _, t := range p.Tools {
		if mutatingTools[t] {
			return KindSkill
		}
	}
	return KindSubagent
}

// ScaffoldSkill writes a SKILL.md scaffold under <root>/.claude/skills/<name>/,
// shaped so the SkillIndex (T-050) discovers it and BM25 (T-051) can rank it.
// It refuses to overwrite an existing scaffold.
func ScaffoldSkill(root, name string, p Pattern) (string, error) {
	if err := validName(name); err != nil {
		return "", err
	}
	path := filepath.Join(root, ".claude", "skills", name, "SKILL.md")
	body := fmt.Sprintf(`---
name: %s
description: %s
---

# %s

Distilled from %d recorded runs that used this tool sequence.

## Observed sequence
%s

## Steps
%s

> Generated by /distill. Edit freely — /distill never overwrites an existing file.
`,
		name,
		describe(p),
		name,
		p.Runs,
		"`"+strings.Join(p.Tools, " → ")+"`",
		numberedSteps(p.Tools),
	)
	return writeNew(path, body)
}

// ScaffoldCommand writes a command scaffold under <root>/.opencode/command/.
func ScaffoldCommand(root, name string, p Pattern) (string, error) {
	if err := validName(name); err != nil {
		return "", err
	}
	path := filepath.Join(root, ".opencode", "command", name+".md")
	body := fmt.Sprintf(`---
name: %s
description: %s
---

Run the distilled sequence: %s

Seen in %d recorded runs.

> Generated by /distill. Edit freely — /distill never overwrites an existing file.
`,
		name, describe(p), "`"+strings.Join(p.Tools, " → ")+"`", p.Runs)
	return writeNew(path, body)
}

// ScaffoldSubagent writes a subagent scaffold under <root>/.opencode/agent/,
// declaring the tools the mined sequence actually needs.
func ScaffoldSubagent(root, name string, p Pattern) (string, error) {
	if err := validName(name); err != nil {
		return "", err
	}
	path := filepath.Join(root, ".opencode", "agent", name+".md")
	body := fmt.Sprintf(`---
name: %s
description: %s
tools: %s
---

# %s

Distilled from %d recorded runs. Scope this subagent to the sequence below and
nothing more — a narrow subagent is what makes delegation cheap.

## Observed sequence
%s

> Generated by /distill. Edit freely — /distill never overwrites an existing file.
`,
		name, describe(p), strings.Join(dedupeTools(p.Tools), ", "),
		name, p.Runs, "`"+strings.Join(p.Tools, " → ")+"`")
	return writeNew(path, body)
}

// describe builds the frontmatter description — the text BM25 ranks against, so
// it names the tools rather than being generic boilerplate.
func describe(p Pattern) string {
	return fmt.Sprintf("Repeated %s workflow (%d runs)",
		strings.Join(dedupeTools(p.Tools), "+"), p.Runs)
}

func numberedSteps(tools []string) string {
	var b strings.Builder
	for i, t := range tools {
		fmt.Fprintf(&b, "%d. `%s` — describe what this step should do.\n", i+1, t)
	}
	return b.String()
}

// dedupeTools lists each tool once, preserving first-use order.
func dedupeTools(tools []string) []string {
	seen := map[string]bool{}
	out := make([]string, 0, len(tools))
	for _, t := range tools {
		if seen[t] {
			continue
		}
		seen[t] = true
		out = append(out, t)
	}
	return out
}

// validName rejects empty names and anything with path separators, so a
// generated name can never escape its scaffold directory.
func validName(name string) error {
	if strings.TrimSpace(name) == "" {
		return fmt.Errorf("improve: scaffold name is empty")
	}
	if strings.ContainsAny(name, `/\`) || name == "." || name == ".." {
		return fmt.Errorf("improve: invalid scaffold name %q", name)
	}
	return nil
}

// writeNew creates a file, refusing to clobber an existing one so hand-edits
// survive later /distill runs.
func writeNew(path, body string) (string, error) {
	if _, err := os.Stat(path); err == nil {
		return "", fmt.Errorf("improve: %s already exists (not overwriting)", path)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", fmt.Errorf("improve: mkdir: %w", err)
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		return "", fmt.Errorf("improve: write scaffold: %w", err)
	}
	return path, nil
}

// newSkillIndex builds a SkillIndex over roots — used to prove a distilled
// skill is discoverable by the index it was generated for.
func newSkillIndex(roots ...string) *skills.Index {
	return skills.NewIndex(roots...)
}
